project:
  version: 1.0.0

server:
  port: 8001
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: SeckillSystemManager
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill_system?useUnicode=true&chatacterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: hbjKA737489
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
