auth:
  app-key: IZe37zbJnGpPrZ5u
  secret: 123
  expired-time: 3000
  sign-expired-time: 60 # 分

weixin:
  appid: wx3f7f4b71b02fb7ab
  secret: 0728701dbff0f9d33e29e65d59e57147

server:
  port: 8811

spring:
  application:
    name: bank-gateway
    url: localhost:8811

  boot:
    admin:
      client:
        url: http://localhost:8811

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: bank-manager-service
          uri: lb://bank-manager
          predicates:
            - Path=/web/**
        - id: bank-seckill-service
          uri: lb://bank-seckill
          predicates:
            - Path=/weixin/seckill/**
        - id: bank-order-service
          uri: lb://bank-order
          predicates:
            - Path=/weixin/**

springdoc:
  swagger-ui:
    configUrl: /swagger-config.json

