auth:
  secret: 123
  expired-time: 3000

weixin:
  appid: wx3f7f4b71b02fb7ab
  secret: 0728701dbff0f9d33e29e65d59e57147

server:
  port: 8811


spring:
  application:
    name: bank-gateway
    url: localhost:8811

  boot:
    admin:
      client:
        url: http://loalhost:8812

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: web-service
          uri: lb://bank-manager
          predicates:
            - Path=/web/**
        - id: order-service
          uri: lb://bank-order
          predicates:
            - Path=/weixin/**

springdoc:
  swagger-ui:
    configUrl: /swagger-config.json

