auth:
  secret: 123
  expired-time: 3000


spring:
  application:
    name: bank-auth

  cloud:
    nacos:
      discovery:
        server-addr: 112.74.189.224:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bank-manager-router
          uri: lb://bank-manager
          predicates:
            - Path=/admin/**