auth:
  secret: 123
  expired-time: 3000


spring:
  application:
    name: bank-auth

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.70.96.169:3306/seckill_system?useUnicode=true&chatacterEncoding=utf-8&useSSL=false
    username: root
    password: hbjKA737489