spring:
  redis:
    host: host.docker.internal
    password: 73wjWEqnrcPG1fJd
    lettuce:
      pool:
        max-active: 200
        max-idle: 160
        min-idle: 4

  cloud:
    nacos:
      discovery:
        server-addr: host.docker.internal:8848
  rabbitmq:
    username: admin
    password: admin
    host: host.docker.internal
    port: 5672
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 2
          max-attempts: 3
          stateless: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.32.230:3306/sxfcds2104046?useUnicode=true&chatacterEncoding=utf-8&useSSL=false
    username: sxfcds2104046
    password: SX_fcds2104046
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  boot:
    admin:
      client:
        url: http://host.docker.internal:8812

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: ./logs/${spring.application.name}/info.log
  config: classpath:logback-spring.xml
path:
  log: ./logs/${spring.application.name}