server:
  port: 8090
  servlet:
    context-path: /weixin

spring:
  application:
    name: bank-order
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  cloud:
    nacos:
      discovery:
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
sec-kill:
  url:
    key: 33oWwIws6iQnZWZc